# Generated by Django 3.0.1 on 2019-12-21 22:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticketing', '0002_auto_20191221_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='assigned_to',
            field=models.ManyToManyField(related_name='assigned_ticket', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='submitted_by',
            field=models.ManyToManyField(related_name='submitted_ticket', to=settings.AUTH_USER_MODEL),
        ),
    ]
