# Generated by Django 3.0.1 on 2019-12-21 23:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticketing', '0003_auto_20191221_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='ticket',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_ticket', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='submitted_by',
        ),
        migrations.AddField(
            model_name='ticket',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_ticket', to=settings.AUTH_USER_MODEL),
        ),
    ]
