# Generated by Django 3.0.1 on 2019-12-25 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ticketing.constants


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticketing', '0005_auto_20191221_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_ticket', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('LOW', 'low'), ('MEDIUM', 'medium'), ('HIGH', 'high')], default=ticketing.constants.TicketPriority['MEDIUM'], max_length=30),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('NEW', 'new'), ('TRIAGED', 'triaged'), ('ON_HOLD', 'on hold'), ('DONE', 'done')], default=ticketing.constants.TicketStatus['NEW'], max_length=30),
        ),
    ]
