# Generated by Django 3.0.1 on 2019-12-25 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('ticketing', '0006_auto_20191225_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='ticket',
            name='assignee_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='assignee_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('LOW', 'low'), ('MEDIUM', 'medium'), ('HIGH', 'high')], default='medium', max_length=30),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('NEW', 'new'), ('TRIAGED', 'triaged'), ('ON_HOLD', 'on hold'), ('DONE', 'done')], default='new', max_length=30),
        ),
        migrations.CreateModel(
            name='AssignedAnonymousUser',
            fields=[
                ('assignee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ticketing.Assignee')),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('slack_id', models.CharField(blank=True, max_length=60, null=True)),
            ],
            bases=('ticketing.assignee',),
        ),
        migrations.CreateModel(
            name='AssignedTeam',
            fields=[
                ('assignee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ticketing.Assignee')),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('slack_id', models.CharField(blank=True, max_length=60, null=True)),
            ],
            bases=('ticketing.assignee',),
        ),
        migrations.CreateModel(
            name='AssignedUser',
            fields=[
                ('assignee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ticketing.Assignee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('ticketing.assignee',),
        ),
    ]
