# Generated by Django 3.0.1 on 2019-12-26 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0007_auto_20191225_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignedteam',
            name='email',
        ),
        migrations.RemoveField(
            model_name='assignedteam',
            name='slack_id',
        ),
    ]
