# Generated by Django 3.0.1 on 2019-12-26 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0008_auto_20191226_2035'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssignedTeam',
        ),
    ]
