# Generated by Django 3.0.1 on 2019-12-26 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '__first__'),
        ('ticketing', '0009_delete_assignedteam'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedTeam',
            fields=[
                ('assignee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ticketing.Assignee')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='account.Team')),
            ],
            bases=('ticketing.assignee',),
        ),
    ]
