# Generated by Django 3.0.1 on 2019-12-30 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticketing', '0010_assignedteam'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedUser',
            fields=[
                ('assignee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ticketing.Assignee')),
                ('slack_id', models.CharField(max_length=100, null=True, unique=True)),
                ('email', models.CharField(max_length=100, null=True, unique=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
            bases=('ticketing.assignee',),
        ),
    ]
